### PR TITLE
Add AttachmentField

### PR DESCRIPTION
**Pull request by grayswan**
* Adds AttachmentField
* Updates deps to resolve security warnings
* Remove unused files

### CODE REVIEW

**Review by chrisworkmode — APPROVED** [review]

**Comment by chrisworkmode** [comment]
Do we need to rebuild and commit the dist? It looks like the dist is commited to the repo?

**Review by toddrun — APPROVED** [review]
Seems 100% reasonable and typo-free

**Comment by jahndis** [comment]
> Do we need to rebuild and commit the dist? It looks like the dist is commited to the repo?

I can take care of that as part of the release process.

**Review by ekatocd — APPROVED** [review]

**Review by chrisgregorysni — APPROVED** [review]

**Comment by jahndis** [comment]
Full disclosure, I really don't know how this repo gets used, so bear that in mind:
- Does anything need to be added to `src/schemas/postgres-query-v2.js` or `src/schemas/postgres-schema.js`? I see a bunch of the other media types in those files.
- Does a module for attachments need to be added like `src/schemas/postgres/attachments.js`?
- Does `attachment_usage` and `attachment_count` need to be added to `src/schemas/postgres/forms.js`?

Again, I just searched for where photos were used, and am mostly following that, so these might not be real issues.

**Comment by chrisworkmode** [comment]
> Full disclosure, I really don't know how this repo gets used, so bear that in mind:
> 
>     * Does anything need to be added to `src/schemas/postgres-query-v2.js` or `src/schemas/postgres-schema.js`? I see a bunch of the other media types in those files.
> 
>     * Does a module for attachments need to be added like `src/schemas/postgres/attachments.js`?
> 
>     * Does `attachment_usage` and `attachment_count` need to be added to `src/schemas/postgres/forms.js`?

I could be completely wrong, but I'm assuming anything in schema represents the actually db schema so if there were no changes there then we won't need anything here? Just a guess.

**Review by zhm — APPROVED** [review]
👍

**Pull request merged**
